### ISSUE TITLE
change game logic functions to take parameters

### ISSUE THREAD

**Issue by carlbell** [carlbell/battleship#4]
instead of cin

**Comment by bbb222222** [comment]
Assume the logic function asks the player for input by returning a string as output and the input is taken using the parameters. How is the player supposed to know what parameter to input beforehand if the function return is the text asking the player for the input?

Possibly, a separate prompt function could be made, but this would require calling two functions and remove some of the C++ logic and purpose.

Essential problem: The cin part comes after the text explaining what should be input

**Comment by carlbell** [comment]
the logic function does not need to do any prompting, because the method of prompting will probably change a lot based on medium of the game and the game logic functions should be pretty much agnostic to where they're being used, ie, the prompt is done by the front end code, then the front end calls the game logic with the users response to the prompt

**Comment by carlbell** [comment]
another option is that each function gives as part of its return struct the message that should be given to the user before the previous next game logic function is called

**Comment by carlbell** [comment]
or per @bbb222222 , call without args and function will return prompt to give user to get info to call with args

**Comment by bbb222222** [comment]
I will implement the last suggestion.
